### ISSUE TITLE
Clarification regarding Generator's defimpl for Any

### ISSUE THREAD

**Issue by cognivore** [witchcrafters/type_class#45]
What is [`Any`](https://github.com/witchcrafters/type_class/blob/442bbfbac336231351feecb83ec7bc9ccbe07a57/lib/type_class/property/generator.ex#L31)? I can't find it neither in the code of `type_class` nor in Elixir's docs.

**Comment by florius0** [comment]
https://elixir-lang.org/getting-started/protocols.html#implementing-any
